Use external env vars in redis credentials script (#9)
* Move env variables to snapcraft.yaml

* Update logger to use `$SNAP_INSTANCE_NAME` as prefix

* Use `LOG_PREFIX`

* Add `set -e` to exit immediately if a non-zero status returned

diff --git a/snap/local/runtime-helpers/bin/setup-redis-credentials b/snap/local/runtime-helpers/bin/setup-redis-credentials
--- a/snap/local/runtime-helpers/bin/setup-redis-credentials
+++ b/snap/local/runtime-helpers/bin/setup-redis-credentials
@@ -1,11 +1,17 @@
 #!/bin/bash
 
-logger "edgex-ekuiper:redis-token-setup: started"
+set -e
 
-VAULT_TOKEN_FILE=$SNAP_DATA/edgex-ekuiper/secrets-token.json
-REDIS_TOKEN_FILE=$SNAP_DATA/edgex-ekuiper/redis.yaml
-SOURCE_FILE=$SNAP_DATA/etc/sources/edgex.yaml 
-CONNECTIONS_FILE=$SNAP_DATA/etc/connections/connection.yaml
+LOG_PREFIX=$SNAP_INSTANCE_NAME:configure-kuiper
+
+logger "$LOG_PREFIX: started"
+
+for var in VAULT_TOKEN_FILE SOURCE_FILE CONNECTION_FILE ; do
+	if [ -z "${!var}" ] ; then
+		logger --stderr "$LOG_PREFIX: $var is not set"
+		exit 1
+	fi
+done
 
 handle_error()
 {
@@ -13,7 +19,7 @@ handle_error()
 	local ITEM=$2
 	local RESPONSE=$3
 	if [ $EXIT_CODE -ne 0 ] ; then
-		logger --stderr "edgex-ekuiper:redis-token-setup: $ITEM exited with code $EXIT_CODE: $RESPONSE"
+		logger --stderr "$LOG_PREFIX: $ITEM exited with code $EXIT_CODE: $RESPONSE"
 		exit 1
 	fi
 }
@@ -21,7 +27,7 @@ handle_error()
 # use Vault token query Redis token, access edgexfoundry secure Message Bus
 if [ -f "$VAULT_TOKEN_FILE" ] ; then
 	# get Vault token and create redis.yaml
-	logger "edgex-ekuiper:redis-token-setup: using Vault token to query Redis token"
+	logger "$LOG_PREFIX: using Vault token to query Redis token"
 	TOKEN=$(yq "$VAULT_TOKEN_FILE" | yq ' .auth.client_token')
 	handle_error $? "yq" $TOKEN
 
@@ -34,13 +40,13 @@ if [ -f "$VAULT_TOKEN_FILE" ] ; then
 	# check response http code
 	HTTP_CODE="${CURL_RES:${#CURL_RES}-3}"
 	if [ $HTTP_CODE -ne 200 ] ; then
-		logger --stderr "edgex-ekuiper:redis-token-setup: http error $HTTP_CODE, with response: $CURL_RES"
+		logger --stderr "$LOG_PREFIX: http error $HTTP_CODE, with response: $CURL_RES"
 		exit 1
 	fi
 
 	# get CURL's reponse
 	if [ ${#CURL_RES} -eq 3 ]; then
-		logger --stderr "edgex-ekuiper:redis-token-setup: unexpected http response with empty body"
+		logger --stderr "$LOG_PREFIX: unexpected http response with empty body"
 		exit 1
 	else
 		BODY="${CURL_RES:0:${#CURL_RES}-3}"
@@ -53,17 +59,17 @@ if [ -f "$VAULT_TOKEN_FILE" ] ; then
 	handle_error $? "yq" $REDIS_PASS
 
 	# pass generated Redis credentials to configuration files
-	logger "edgex-ekuiper:redis-token-setup: adding Redis credentials to $SOURCE_FILE"
+	logger "$LOG_PREFIX: adding Redis credentials to $SOURCE_FILE"
 	YQ_RES=$(yq -i '.default += {"optional":{"Username":"'$REDIS_USER'"}+{"Password":"'$REDIS_PASS'"}}' "$SOURCE_FILE")
 	handle_error $? "yq" $YQ_RES
 	
-	logger "edgex-ekuiper:redis-token-setup: adding Redis credentials to $CONNECTIONS_FILE"
-	YQ_RES=$(yq -i '.edgex.redisMsgBus += {"optional":{"Username":"'$REDIS_USER'"}+{"Password":"'$REDIS_PASS'"}}' "$CONNECTIONS_FILE")
+	logger "$LOG_PREFIX: adding Redis credentials to $CONNECTION_FILE"
+	YQ_RES=$(yq -i '.edgex.redisMsgBus += {"optional":{"Username":"'$REDIS_USER'"}+{"Password":"'$REDIS_PASS'"}}' "$CONNECTION_FILE")
 	handle_error $? "yq" $YQ_RES
 
-	logger "edgex-ekuiper:redis-token-setup: configured eKuiper to authenticate with Redis, using credentials fetched from Vault"
+	logger "$LOG_PREFIX: configured eKuiper to authenticate with Redis, using credentials fetched from Vault"
 else
-	logger --stderr "edgex-ekuiper:redis-token-setup: unable to configure eKuiper to authenticate with Redis: unable to query Redis token from Vault: Vault token not available"
+	logger --stderr "$LOG_PREFIX: unable to configure eKuiper to authenticate with Redis: unable to query Redis token from Vault: Vault token not available"
 fi
 
 exec "$@"
